const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const ROOT=path.resolve(__dirname,'../..'),html=fs.readFileSync(path.join(ROOT,'index.html'),'utf8');
const E=require('../../assets/experience/experience.js');
test('levels advance after every unique correct answer and cap at ten',()=>{const s={};for(let i=0;i<25;i++){E.solve(s,'Q'+i);assert.equal(E.levelFor(E.solvedCount(s)),Math.min(10,2+i));}assert.equal(E.solve(s,'Q0'),false);assert.equal(E.solvedCount(s),25);});
test('all inline scripts parse',()=>{let count=0;for(const m of html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)){new vm.Script(m[1]);count++;}assert.ok(count>3);});
function section(start,end){return html.slice(html.indexOf(start),html.indexOf(end,html.indexOf(start)));}
function world(){
 const storage=new Map(),els=new Map();const el=id=>{if(!els.has(id))els.set(id,{textContent:'',innerHTML:'',className:'',disabled:false,hidden:false,classList:{add(){},remove(){},toggle(){}},insertAdjacentHTML(){}});return els.get(id);};
 const context={console,crypto,performance,window:{addEventListener(){}},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},document:{readyState:'loading',documentElement:{dataset:{}},addEventListener(){},getElementById:el,querySelectorAll:()=>[]},matchMedia:()=>({matches:false}),navigator:{userAgent:'test'},$:el,app:{user:{user_id:'u'}},session:{token:'tok'},testEscape:String,testHintHTML:String,outputPreHTML:String,ClickChapter:{cleanExplanation:x=>x},ClickGlossary:{linkify:x=>x},DADA_HALF:{},KABI:{},getTestAudio(){},testCorrectSound(){},testWrongFeedback(){},animateTestXP(){},animateTestWrong(){},bindTestHints(){},replayTestClass(){},setTimeout:fn=>fn(),toast(){},currentTestAnswer:()=>context.answer,cachedAnswerCorrect:(q,a)=>q.answer===a,renderTest(){context.testState.deferred=false;context.testState.answered=false;},finishReview:async()=>{context.finished=true},finishChapter:async()=>{context.finished=true},post:async()=>({pending_xp:1,hearts:3})};
 context.addEventListener=()=>{};context.window=context;vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(ROOT,'assets/experience/experience.js'),'utf8'),context);context.ClickExperience.setCount=n=>context.count=n;context.ClickExperience.advance=()=>context.count=(context.count||0)+1;context.ClickExperience.feedback=()=>{};
 vm.runInContext(section('function masteryKey(', '// ---------------- unified chapter run:'),context);
 vm.runInContext(section('async function checkTestAnswer(){','function showChapterDone('),context);
 context.currentSlide=()=>context.testState.slides[context.testState.index];
 const q=id=>({question_id:id,type:'MCQ',answer:'yes',xp:1,explanation:''});const qs=[q('A'),q('B'),q('C')];context.testState={questions:qs,slides:qs.map(q=>({kind:'question',q})),index:0,mode:'review',solved:{},questionAttempts:{},hearts:3,pending:0,stage_id:'S',chapter_id:'CH',test:{chapter_title:'Chapter'},outbox:[]};return context;
}
test('real answer handler defers after three mistakes, retries at end, prevents early finish',async()=>{
 const c=world();c.answer='no';await c.checkTestAnswer();await c.checkTestAnswer();await c.checkTestAnswer();assert.equal(c.testState.slides.length,4);assert.equal(c.testState.slides[3].q.question_id,'A');assert.equal(c.testState.questionAttempts.A,0);assert.equal(c.testState.deferred,true);assert.equal(c.testState.hearts,3);
 const saved=c.ClickExperience.read('clickMastery:u:CH');assert.equal(saved.deferred,true);assert.equal(saved.slides[3].q.question_id,'A');
 await c.nextTestRound();assert.equal(c.testState.index,1);c.answer='yes';await c.checkTestAnswer();await c.nextTestRound();await c.checkTestAnswer();assert.equal(c.count,2);await c.nextTestRound();assert.equal(c.testState.index,3);assert.equal(c.finished,undefined);
 c.answer='no';await c.checkTestAnswer();await c.checkTestAnswer();await c.checkTestAnswer();assert.equal(c.testState.slides.length,5);await c.nextTestRound();c.answer='yes';await c.checkTestAnswer();await c.nextTestRound();assert.equal(c.finished,true);assert.equal(Object.keys(c.testState.solved).length,3);
});
test('persistent outbox survives network errors, retries same request, does not duplicate XP',async()=>{
 const c=world();c.testState.mode='graded';c.testState.test_run_id='run';let calls=0,ids=[];c.post=async(action,payload)=>{calls++;ids.push(payload.client_attempt_id);if(calls===1)throw Error('offline');return{pending_xp:1,hearts:3}};
 c.answer='yes';await c.checkTestAnswer();await c.testState.syncChain;assert.equal(c.testState.outbox.length,1);const saved=c.ClickExperience.read('clickMastery:u:CH');assert.equal(saved.outbox.length,1);assert.equal(saved.solved.A,true);await c.waitForTestSync();assert.equal(c.testState.outbox.length,0);assert.equal(ids[0],ids[1]);assert.equal(c.testState.pending,1);
});
test('audio manager loops all ten assets at matching phase, crossfades, and obeys mute',async()=>{
 const handlers={},els=new Map();const param=()=>({value:0,setValueAtTime(v){this.value=v},linearRampToValueAtTime(v){this.value=v},setTargetAtTime(v){this.value=v},cancelScheduledValues(){}});
 const elem=id=>{if(!els.has(id))els.set(id,{textContent:'',value:'',setAttribute(){},appendChild(){}});return els.get(id);};const sources=[],gains=[],fetches=[];
 class Audio{constructor(){this.currentTime=12;this.state='running';this.destination={};}resume(){return Promise.resolve()}createGain(){const g={gain:param(),connect(){}};gains.push(g);return g}createDynamicsCompressor(){return{connect(){}}}decodeAudioData(){return Promise.resolve({duration:30})}createBufferSource(){const s={connect(){},start(t,offset){this.offset=offset},stop(){this.stopped=true}};sources.push(s);return s}}
 const c={console,performance,AudioContext:Audio,fetch:async url=>{fetches.push(url);return{ok:true,arrayBuffer:async()=>new ArrayBuffer(1)}},localStorage:{getItem:()=>null,setItem(){}},document:{readyState:'loading',hidden:false,documentElement:{dataset:{}},querySelectorAll:()=>[],addEventListener:(n,fn)=>handlers[n]=fn,getElementById:elem,createElement:()=>({setAttribute(){}}),body:{appendChild(){}}},matchMedia:()=>({matches:true})};c.window=c;vm.createContext(c);vm.runInContext(fs.readFileSync(path.join(ROOT,'assets/experience/experience.js'),'utf8'),c);handlers.DOMContentLoaded();await c.ClickExperience.unlock();assert.equal(sources[0].loop,true);assert.equal(sources[0].offset,0);
 for(let n=2;n<=10;n++){c.ClickExperience.setCount(n-1);await new Promise(r=>setImmediate(r));assert.equal(c.document.documentElement.dataset.level,String(n));assert.equal(sources.at(-1).loop,true);assert.equal(sources.at(-2).stopped,true);assert.equal(sources.at(-1).offset,0);}
 assert.ok(fetches.includes('assets/experience/music/level-10.wav'));elem('experienceMusic').onclick();assert.equal(gains[1].gain.value,0);assert.equal(elem('experienceMusic').textContent,'Music off');
});
