-- Stage-0 "Foundations" content (Phase 1): adds the new 5-chapter Stage 0
-- (Intro, printf, Comments, Variables, Recap & Datatypes Intro) sourced verbatim
-- from stage-4 ch 1.pdf, deactivates the old 30-chapter "Constants, Variables and
-- Data Types" stage (STG000) without deleting it, and repoints the Practice Bank
-- unlock prerequisite (P001) from STG000 to the new STG001.
--
-- Hand-written (not generated by admin-tools/build-content-migration.js) because
-- admin-tools/.admin-key is not present in this environment, so the script's live
-- adminGetMaxIds backend call could not be made. Next-IDs below were derived by hand
-- from the CSV exports under CSVs/ (max chapter CH0030, max question Q000150, max
-- option O0000360, max glossary term TERM030) and cross-checked against the SQL this
-- script would itself emit for stages/chapters/learn_content/questions/options/
-- test_hints/question_terms, so the statement grouping and ID conventions match.

-- stages
insert into stages (stage_id, stage_no, title, "order", active) values ('STG001', 0, 'Foundations', 0, true);

-- glossary
insert into glossary (term_id, term, definition, color, aliases, active) values ('TERM031', 'programming language', 'A language used to give instructions to a computer.', '#5867d8', '', true);
insert into glossary (term_id, term, definition, color, aliases, active) values ('TERM032', 'first stage', 'The beginning step of a process.', '#5867d8', '', true);
insert into glossary (term_id, term, definition, color, aliases, active) values ('TERM033', 'programming', 'The process of creating instructions for a computer.', '#5867d8', '', true);
insert into glossary (term_id, term, definition, color, aliases, active) values ('TERM034', 'source code', 'Instructions written by a programmer.', '#5867d8', '', true);
insert into glossary (term_id, term, definition, color, aliases, active) values ('TERM035', 'stage', 'A step in a process.', '#5867d8', '', true);
insert into glossary (term_id, term, definition, color, aliases, active) values ('TERM036', 'machine-understandable', 'A form that a computer can understand.', '#5867d8', '', true);
insert into glossary (term_id, term, definition, color, aliases, active) values ('TERM037', 'required files', 'Files needed for the program to work.', '#5867d8', '', true);
insert into glossary (term_id, term, definition, color, aliases, active) values ('TERM038', 'libraries', 'Collections of ready-made code.', '#5867d8', '', true);
insert into glossary (term_id, term, definition, color, aliases, active) values ('TERM039', 'final program', 'The completed program.', '#5867d8', '', true);
insert into glossary (term_id, term, definition, color, aliases, active) values ('TERM040', 'execution', 'The process of running a program.', '#5867d8', '', true);
insert into glossary (term_id, term, definition, color, aliases, active) values ('TERM041', 'program', 'A set of instructions given to a computer.', '#5867d8', '', true);
insert into glossary (term_id, term, definition, color, aliases, active) values ('TERM042', 'output', 'The result produced by a program.', '#5867d8', '', true);
insert into glossary (term_id, term, definition, color, aliases, active) values ('TERM043', 'Build', 'To create or develop something.', '#5867d8', '', true);
insert into glossary (term_id, term, definition, color, aliases, active) values ('TERM044', 'printf()', 'A function used to display output.', '#5867d8', '', true);
insert into glossary (term_id, term, definition, color, aliases, active) values ('TERM045', 'main()', 'The main function where a C program starts running.', '#5867d8', '', true);
insert into glossary (term_id, term, definition, color, aliases, active) values ('TERM046', 'structure', 'The basic arrangement or organization of something.', '#5867d8', '', true);
insert into glossary (term_id, term, definition, color, aliases, active) values ('TERM047', 'syntax', 'The rules for writing code correctly.', '#5867d8', '', true);
insert into glossary (term_id, term, definition, color, aliases, active) values ('TERM048', 'comment', 'A note written in a program to explain something.', '#5867d8', '', true);
insert into glossary (term_id, term, definition, color, aliases, active) values ('TERM049', 'symbol', 'A special character used in code.', '#5867d8', '', true);
insert into glossary (term_id, term, definition, color, aliases, active) values ('TERM050', 'single-line', 'Something that exists or happens on one line.', '#5867d8', '', true);
insert into glossary (term_id, term, definition, color, aliases, active) values ('TERM051', 'multi-line', 'Something that continues across more than one line.', '#5867d8', '', true);
insert into glossary (term_id, term, definition, color, aliases, active) values ('TERM052', 'execute', 'To run or perform an instruction.', '#5867d8', '', true);
insert into glossary (term_id, term, definition, color, aliases, active) values ('TERM053', 'statement', 'An instruction written in a program.', '#5867d8', '', true);
insert into glossary (term_id, term, definition, color, aliases, active) values ('TERM054', 'variable', 'A named place used to store information.', '#5867d8', '', true);
insert into glossary (term_id, term, definition, color, aliases, active) values ('TERM055', 'integer', 'A whole number without a decimal part.', '#5867d8', '', true);
insert into glossary (term_id, term, definition, color, aliases, active) values ('TERM056', 'purpose', 'The reason something is used.', '#5867d8', '', true);
insert into glossary (term_id, term, definition, color, aliases, active) values ('TERM057', 'data type', 'Tells C what kind of value is being used.', '#5867d8', '', true);
insert into glossary (term_id, term, definition, color, aliases, active) values ('TERM058', 'whole number', 'A number without a decimal part.', '#5867d8', '', true);
insert into glossary (term_id, term, definition, color, aliases, active) values ('TERM059', 'main purpose', 'The primary reason something is used.', '#5867d8', '', true);
insert into glossary (term_id, term, definition, color, aliases, active) values ('TERM060', 'character', 'A single letter, number, or symbol.', '#5867d8', '', true);
insert into glossary (term_id, term, definition, color, aliases, active) values ('TERM061', 'value', 'Information stored in a variable.', '#5867d8', '', true);
insert into glossary (term_id, term, definition, color, aliases, active) values ('TERM062', 'int', 'A data type used to store whole numbers.', '#5867d8', '', true);
insert into glossary (term_id, term, definition, color, aliases, active) values ('TERM063', 'float', 'A data type used to store decimal numbers.', '#5867d8', '', true);
insert into glossary (term_id, term, definition, color, aliases, active) values ('TERM064', 'char', 'A data type used to store one character.', '#5867d8', '', true);
insert into glossary (term_id, term, definition, color, aliases, active) values ('TERM065', 'display', 'To show something on the screen.', '#5867d8', '', true);
insert into glossary (term_id, term, definition, color, aliases, active) values ('TERM066', 'integer variable', 'A variable used to store a whole number.', '#5867d8', '', true);
insert into glossary (term_id, term, definition, color, aliases, active) values ('TERM067', 'age', 'The number of years a person has lived.', '#5867d8', '', true);
insert into glossary (term_id, term, definition, color, aliases, active) values ('TERM068', 'separate variables', 'Different variables created for different values.', '#5867d8', '', true);
insert into glossary (term_id, term, definition, color, aliases, active) values ('TERM069', 'program structure', 'The basic arrangement of parts in a program.', '#5867d8', '', true);

-- chapters
insert into chapters (chapter_id, stage_id, chapter_no, title, "order", active) values ('CH0031', 'STG001', 1, 'Intro', 1, true);
insert into chapters (chapter_id, stage_id, chapter_no, title, "order", active) values ('CH0032', 'STG001', 2, 'printf', 2, true);
insert into chapters (chapter_id, stage_id, chapter_no, title, "order", active) values ('CH0033', 'STG001', 3, 'Comments', 3, true);
insert into chapters (chapter_id, stage_id, chapter_no, title, "order", active) values ('CH0034', 'STG001', 4, 'Variables', 4, true);
insert into chapters (chapter_id, stage_id, chapter_no, title, "order", active) values ('CH0035', 'STG001', 5, 'Recap & Datatypes Intro', 5, true);

-- learn_content
insert into learn_content (learn_id, stage_id, chapter_id, title, pages_text, active) values ('L_CH0031', 'STG001', 'CH0031', 'Intro', 'Structure in C — First C Program
A C program follows a basic structure. Here is our first C program:

```c
#include <stdio.h>

int main() {
   printf("Hello World!");
   return 0;
}
```

**Output**
```
Hello World!
```

Think of it like a recipe:
- `#include` brings the tools
- `main()` tells C where to start
- `{ }` contains the instructions
- `printf()` displays the result
- `return 0;` tells C the program finished successfully//.//Compiler
**What is a Compiler?**
A compiler is a program that translates the code written by humans into machine language that a computer can understand and run.

**Why do we use it?**
Computers cannot directly understand programming languages like C, C++ or Java. The compiler converts our code into instructions that the computer can execute.

**How does it work?**
Human-readable Code → Compiler → Machine Code → Computer
- C Code — written by the programmer
- Compiler — translates the C code
- Machine Code — instructions understood by the computer
- Output — Hello, World!

**Easy Analogy**
Programmer = Person speaking English. Compiler = Translator. Computer = Person who understands another language. The compiler acts as a translator between the programmer and the computer.

For now, just remember: **Compiler = Code Translator**. It converts human-readable source code into machine-understandable instructions.//.//Syntax
**Simple Definition**
Syntax = Rules for writing C correctly.

Think of it like:
- English: Grammar → Correct sentence
- C: Syntax → Correct program

**Example**
`printf("Hello");` — Correct. The `;` tells C that the statement has ended.
`printf("Hello")` — Missing `;`, so C can report a syntax error.

**Important Symbols**
- `;` — Ends a statement
- `{ }` — Groups statements
- `( )` — Used with functions
- `" "` — Holds text
- `#` — Starts a preprocessor directive

**Easy Memory Trick**
Syntax = C''s Grammar. See → Identify → Fix → Write → Run.//.//Header Files
**What is a Header File?**
A header file contains pre-defined functions and information that we can use in our C program.

**Why do we use it?**
It saves us from writing common functions from scratch and makes programming easier.

Most important for beginners: `stdio.h` — Standard Input/Output. It provides commonly used functions such as:
- `printf()` — displays output
- `scanf()` — takes input

**Example**
```c
#include <stdio.h>

int main()
{
   printf("Hello, World!");
   return 0;
}
```

Here, `#include <stdio.h>` tells C to include the required information from `stdio.h`.

**Easy Analogy**
Header file = Toolbox. Functions = Tools. We include the toolbox we need and use its tools.

Coming later: `string.h`, `math.h`, `stdlib.h`, `ctype.h` and more. For now, just remember: `stdio.h` helps us handle basic input and output in C.//.//Main Function in C — Quick Recap
**What is main()?**
`main()` is a special function in C where the execution of a program begins.

Think of a C program as a building: `main()` = Main Entrance. When the program starts, C enters through `main()` and begins executing the statements inside it.

**Example**
```c
#include <stdio.h>

int main()
{
   printf("Hello World!");
   return 0;
}
```

**What does int main() mean?**
- `int` — tells us the function returns an integer value
- `main()` — the starting point of the program
- `{ }` — contains the statements to be executed
- `return 0;` — indicates the program finished successfully

**Easy Memory Trick**
main() → "C, START HERE!"

**Quick Recap**
- `main()` — Starting point of a C program
- `int` — Return type
- `{ }` — Body of the function
- `return 0;` — Successful completion', true);
insert into learn_content (learn_id, stage_id, chapter_id, title, pages_text, active) values ('L_CH0032', 'STG001', 'CH0032', 'printf', 'What''s printf?
**Simple Definition**
`printf()` is a C function used to display output on the screen. In simple words: you give `printf()` something → C shows it on the screen.

**Example**
```c
printf("Hello!");
```

**Output**
```
Hello!
```

So think: `printf()` = C''s speaker.

**Important Rule**
Whatever you want `printf()` to print as text must be written inside double quotes `" "`.
`printf("Hello World!");` — only the text inside `" "` is printed as text.

- Wrong: `printf(Hello World!);`
- Correct: `printf("Hello World!");`//.//First printf() Program
```c
#include <stdio.h>

int main()
{
       printf("Hello World!");
       return 0;
}
```

**Output**
```
Hello World!
```

**What is happening?**
`#include <stdio.h>` gives access to `printf()` → `printf("Hello World!");` tells C to send "Hello World!" → the Screen shows it.

Takeaway: `printf()` displays what you ask it to display.

**Can Print Different Things**
- Text: `printf("Hello!");` → Output: `Hello!`
- Numbers: `printf("25");` → Output: `25`
- Characters: `printf("A");` → Output: `A`
- Multiple words: `printf("I am learning C!");` → Output: `I am learning C!`

Think of `printf()` like a delivery person: whatever you put inside the `()` is what you are asking `printf()` to work with.//.//New Line \n
Now imagine:
```c
printf("Hello");
printf("World");
```
Output: `HelloWorld` — C didn''t make a new line because we didn''t tell it to.

**Meet \n**
`\n` tells C to move the output to a new line.

**Example**
```c
printf("Hello\n");
printf("World");
```
Output:
```
Hello
World
```

**Analogy — The Elevator**
Think of `\n` as an elevator button that takes you to the next line.

**Multiple new lines**
```c
printf("Hello\n");
printf("I am learning C\n");
printf("Let''s code!");
```
Output:
```
Hello
I am learning C
Let''s code!
```//.//Code Examples
This slide is purely practical.

**Example 1 — One message**
`printf("Hello!");` → Output: `Hello!`

**Example 2 — Two messages**
```c
printf("Hello!");
printf("Welcome!");
```
Output: `Hello!Welcome!`

**Example 3 — Two lines**
```c
printf("Hello!\n");
printf("Welcome!");
```
Output:
```
Hello!
Welcome!
```

**Example 4 — Multiple lines**
```c
printf("I");
printf(" am");
printf(" learning");
printf(" C!");
```
Output: `I am learning C!`

And:
```c
printf("I\n");
printf("am\n");
printf("learning\n");
printf("C!");
```
Output:
```
I
am
learning
C!
```//.//printf() Recap
C CAN TALK! You write `printf("Hello!");` → `printf()` → SCREEN → `Hello!`

**4 Things to Remember**
- `printf()` — Used to display output
- `" "` — Text goes inside double quotes
- `\n` — Moves output to the next line
- `;` — Ends the statement

**Quick Memory Trick**
`printf()` → "C, SAY THIS!"  ·  `\n` → "C, GO DOWN!"

**See it in code**
```c
printf("Hello!\n");
printf("I am learning C!");
```
**Output**
```
Hello!
I am learning C!
```

Level cleared — I can now make C print a message! Next mission: Comments.', true);
insert into learn_content (learn_id, stage_id, chapter_id, title, pages_text, active) values ('L_CH0033', 'STG001', 'CH0033', 'Comments', 'What Are Comments?
**Simple Definition**
Comments are notes written inside a C program. They are written to help humans understand the code. **C does NOT execute comments.**

**Easy Analogy**
Programmer writes a note → C Compiler says "This is just a note!" → Program continues normally.

**Memory Trick**
Comment = Note for humans, not instructions for C.//.//Single-Line Comment
**Meet //**
The easiest comment in C is `//`. Two forward slashes tell C: "Ignore everything after this on this line!"

**Example**
```c
// This is my first C program
printf("Hello!");
```
**Output**
```
Hello!
```

Notice: the comment does NOT appear on the screen. Think of `//` like a STOP SIGN — C stops reading the rest of that line.

**Another Example**
```c
printf("Hello!"); // Prints Hello
```
Output: `Hello!` — the part after `//` is just a note.

**Remember**
`//` = "This line has a note!"//.//Multi-Line Comment
What if we want a BIGGER note? Sometimes we want to write comments using many lines. For this, C provides `/* comment */`.

**Easy Meaning**
`/*` — START COMMENT → write anything → `*/` — END COMMENT. Everything between `/*` and `*/` is treated as a comment.

**Example**
```c
/*
  This is my first program.
  I am learning C.
  This is a comment.
*/
printf("Hello!");
```
**Output**
```
Hello!
```
The three comment lines don''t appear in the output.

**Easy Memory Trick**
Think of it like a box: `/*` OPEN BOX → write your note here → `*/` CLOSE BOX. Everything inside the box = COMMENT.//.//Why Do We Use Comments?
Why write something C doesn''t use? Because humans need explanations!

1. **To explain code** — `// Print a welcome message` then `printf("Welcome!");`
2. **To give information** — `// Student marks program`
3. **To make code easier to understand** — `// Display the student''s name`
4. **To help other programmers** — imagine someone opens your code after 6 months. Without comments: "What is this?" With comments: "Ohhh! Now I understand!"

**Real-Life Analogy**
A package without a label: "What''s inside?" A package with a label: "Books". Comments work like labels on your code!

**Takeaway**
Comments make code easier for humans to read and understand.//.//Comments Recap
Comments = notes for humans. Two basic types:

```
Type          Symbol   Use
Single-line   //       One-line comment
Multi-line    /* */    Comment using multiple lines
```

**Easy Memory Trick**
`//` → ONE LINE. `/* */` → MANY LINES.

**See it in code**
```c
// My first C program
/*
  I am learning C.
  Comments are easy!
*/
printf("Hello C!");
```
**Output**
```
Hello C!
```

**4 Things to Remember**
- Comments are notes
- They help programmers understand code
- C does not execute comments
- `//` = one line | `/* */` = multiple lines

Level cleared — I can now write comments in C! `//` → "ONE LINE NOTE!" · `/* */` → "BIG NOTE BOX!"', true);
insert into learn_content (learn_id, stage_id, chapter_id, title, pages_text, active) values ('L_CH0034', 'STG001', 'CH0034', 'Variables', 'What Is a Variable?
**Simple Definition**
A variable is a name given to a place in memory where we can store a value. In simple words: Variable = A box that stores information.

**Think of a Variable Like a Box**
Imagine a box labeled AGE containing 18.
- Name of box → `age`
- Value inside → `18`

**In C**
```c
int age = 18;
```
Here: `age` = variable name, `18` = value, `int` = type of value.

**Easy Memory Trick**
Variable = Named Box. The box has a name and stores a value.

**Takeaway**
Variables help us store information in a C program.//.//Creating a Variable
**How do we create a variable?**
Before using a variable, we usually tell C: (1) what type of value? (2) what is its name?

**Simple Formula**
`DATA TYPE + VARIABLE NAME;`

**Example**
```c
int age;
```
This means: "Create a box called age that can store an integer."

**Some Simple Data Types**

```
Type    Stores            Example
int     Whole numbers     25
float   Decimal numbers   25.5
char    One character     ''A''
```

**Remember**
Data type = What kind of value? Variable name = What should we call the box?//.//Storing a Value
Now let''s PUT something inside the box! We can give a variable a value using `=`. The `=` symbol is called the assignment operator.

**Example**
```c
int age;
age = 18;
```
C stores 18 inside the variable `age`. Think of `=` like putting something into a box.

We can also do it in ONE line!
```c
int age = 18;
```

**Easy Memory Trick**
`=` means "Put this value into this variable."

**Takeaway**
`int age = 18;` means: Create `age` → Put 18 inside it.//.//Using a Variable
**Can we use the value later?** YES! Once we store a value in a variable, we can use that variable in our program.

**Example**
```c
#include <stdio.h>

int main()
{
   int age = 18;
   printf("%d", age);
   return 0;
}
```
**Output**
```
18
```

**Important**
When we want to print an int variable using `printf()`, we use `%d`. So `printf("%d", age);` means: "Print the integer value stored in age!"

**Another Example**
```c
int marks = 95;
printf("%d", marks);
```
Output: `95`

**Memory Trick**
Variable stores → printf() shows.//.//Variables Recap
Variables = named storage boxes.

**4 Things to Remember**
- Variable — Stores a value
- Data type — Tells C what type of value it is
- Variable name — Gives the box a name
- `=` — Assigns a value to the variable

**See it all together**
```c
int age = 18;
```
`int` → what type? · `age` → box name · `=` → put value · `18` → value

**Easy Memory Trick**
VARIABLE = BOX · NAME = LABEL · VALUE = WHAT''S INSIDE

**Quick Example**
```c
int age = 18;
int marks = 95;
char grade = ''A'';
```
Think: age → 18, marks → 95, grade → A.

Level cleared — I can now create and use variables in C! A variable is a named box used to store information in a C program.', true);
insert into learn_content (learn_id, stage_id, chapter_id, title, pages_text, active) values ('L_CH0035', 'STG001', 'CH0035', 'Recap & Datatypes Intro', 'Let''s Recap!
Before we learn something new, let''s quickly remember the basics!

**C Programming**
C is a programming language that helps us give instructions to a computer.

**Comments**
Comments are notes written for programmers.
```c
// This is a comment
```
C does not execute the comment.

**Variables**
A variable is like a box that stores a value.
```c
int age = 18;
```

**printf()**
`printf()` is used to display information on the screen.
```c
printf("Hello!");
```
**Output:** `Hello!`

**Quick Memory**
Comment → Explain · Variable → Store · printf() → Display · C → Communicate with the computer//.//Put Everything Together!
Look at this simple program:
```c
#include <stdio.h>

int main()
{
   // Store my age
   int age = 18;
   printf("%d", age);
   return 0;
}
```

**What is happening?**
- `int age = 18;` — We create a variable and store 18.
- `// Store my age` — This is a comment.
- `printf()` — It tells C to display the value.

**Output**
```
18
```

**Follow the journey**
Write code → Add a note → Store information → Display information → See the output.

**Remember!**
Comment → Human reads it · Variable → C stores it · printf() → Screen shows it//.//What Is a Data Type?
We have a variable... but C needs to know: "What kind of value are you storing?" That''s the job of a DATA TYPE!

**Simple Definition**
A data type tells C what kind of data a variable stores.

**Think About Boxes!**
Imagine different boxes: Box A holds 25, Box B holds 25.5, Box C holds ''A''. They all store different kinds of information, so C needs different data types to identify them.

**Easy Real-Life Example**
Imagine a school bag: a books section, a lunch section, a bottle section. Each section is meant for a different type of thing. Similarly, a DATA TYPE answers "What kind of data is this?"

**Golden Memory Trick**
VARIABLE = WHERE we store · DATA TYPE = WHAT we store//.//Basic Data Types
Let''s meet the three basic types!

**int**
Used to store whole numbers. Examples: 10, 25, 100, -5.
```c
int age = 18;
```

**float**
Used to store decimal numbers. Examples: 10.5, 25.75, 3.14.
```c
float price = 25.5;
```

**char**
Used to store one character. Examples: ''A'', ''B'', ''7''.
```c
char grade = ''A'';
```

**Easy Look**

```
Data Type   Stores            Example
int         Whole number      25
float       Decimal number    25.5
char        One character     ''A''
```

**Memory Trick**
int → Whole number · float → Decimal number · char → Character. First understand what they store — don''t worry about memorizing everything yet!//.//Quick Recap + New Learning!
We''ve got the basics! Remember these:

- **C** — A language used to communicate with computers.
- **Comment** — A note for the programmer. `// Hello!`
- **Variable** — A named storage box. `int age = 18;`
- **printf()** — Displays information on the screen. `printf("%d", age);`
- **Data Type** — Tells C what kind of data we are storing.
```c
int age = 18;
float price = 25.5;
char grade = ''A'';
```

**One Big Memory Trick!**
DATA TYPE ("What?") → VARIABLE ("Where?") → VALUE ("Which value?") → printf() ("Show it!") → SCREEN ("Here it is!")', true);

-- questions
insert into questions (question_id, stage_id, chapter_id, type, prompt, code, answer, explanation, hint, xp, "order", active) values ('Q000151', 'STG001', 'CH0031', 'MCQ', 'What is C?', '', 'A programming language', '', 'Think about what C is used for — it is used to create programs.', 1, 1, true);
insert into questions (question_id, stage_id, chapter_id, type, prompt, code, answer, explanation, hint, xp, "order", active) values ('Q000152', 'STG001', 'CH0031', 'MCQ', 'What do we do in the first stage of programming?', '', 'Write/Edit the source code', '', 'Before a computer can run a program, we need to write the code.', 1, 2, true);
insert into questions (question_id, stage_id, chapter_id, type, prompt, code, answer, explanation, hint, xp, "order", active) values ('Q000153', 'STG001', 'CH0031', 'MCQ', 'Which stage checks and converts the C source code into machine-understandable form?', '', 'Compilation', '', 'This stage comes after editing and before the program can be executed.', 1, 3, true);
insert into questions (question_id, stage_id, chapter_id, type, prompt, code, answer, explanation, hint, xp, "order", active) values ('Q000154', 'STG001', 'CH0031', 'MCQ', 'Which stage combines the required files and libraries to create the final program?', '', 'Linking', '', 'Think of the stage that joins everything needed to create the final program.', 1, 4, true);
insert into questions (question_id, stage_id, chapter_id, type, prompt, code, answer, explanation, hint, xp, "order", active) values ('Q000155', 'STG001', 'CH0031', 'MCQ', 'What happens during the execution stage?', '', 'The program is run and produces output', '', 'This is the stage where you finally run the program.', 1, 5, true);
insert into questions (question_id, stage_id, chapter_id, type, prompt, code, answer, explanation, hint, xp, "order", active) values ('Q000156', 'STG001', 'CH0032', 'MCQ', 'Your first output — which function displays something on the screen?', '', 'printf()', '', 'Think about the function that is used to show something on the screen.', 1, 1, true);
insert into questions (question_id, stage_id, chapter_id, type, prompt, code, answer, explanation, hint, xp, "order", active) values ('Q000157', 'STG001', 'CH0032', 'MCQ', 'Build on Q1 — which line correctly prints "Welcome to C"?', '', 'printf("Welcome to C");', '', 'Text that we want to display should be written inside double quotation marks.', 1, 2, true);
insert into questions (question_id, stage_id, chapter_id, type, prompt, code, answer, explanation, hint, xp, "order", active) values ('Q000158', 'STG001', 'CH0032', 'MCQ', 'Build the complete program — which option is a correctly structured C program?', '', 'int main() {
   printf("Hello");
}', '', 'A basic C program needs the main() function and the statement that displays the output.', 1, 3, true);
insert into questions (question_id, stage_id, chapter_id, type, prompt, code, answer, explanation, hint, xp, "order", active) values ('Q000159', 'STG001', 'CH0032', 'MCQ', 'Previous chapter recap: which function acts as the starting point of a C program''s structure?', '', 'main()', '', 'Think about the function that acts as the starting point of a C program.', 1, 4, true);
insert into questions (question_id, stage_id, chapter_id, type, prompt, code, answer, explanation, hint, xp, "order", active) values ('Q000160', 'STG001', 'CH0032', 'MCQ', 'Previous chapter recap: what does the ; symbol mean in C syntax?', '', 'End of the statement', '', 'Look at the symbol ; — it tells C that a statement has ended.', 1, 5, true);
insert into questions (question_id, stage_id, chapter_id, type, prompt, code, answer, explanation, hint, xp, "order", active) values ('Q000161', 'STG001', 'CH0033', 'MCQ', 'What is a comment in C programming?', '', 'A note written for programmers', '', 'Think of a comment as a small note that helps people understand the code.', 1, 1, true);
insert into questions (question_id, stage_id, chapter_id, type, prompt, code, answer, explanation, hint, xp, "order", active) values ('Q000162', 'STG001', 'CH0033', 'MCQ', 'Which symbol is used for a single-line comment?', '', '//', '', 'Look for the symbol that uses two forward slashes.', 1, 2, true);
insert into questions (question_id, stage_id, chapter_id, type, prompt, code, answer, explanation, hint, xp, "order", active) values ('Q000163', 'STG001', 'CH0033', 'MCQ', 'Which symbols are used for a multi-line comment?', '', '/* */', '', 'This comment starts with /* and ends with */.', 1, 3, true);
insert into questions (question_id, stage_id, chapter_id, type, prompt, code, answer, explanation, hint, xp, "order", active) values ('Q000164', 'STG001', 'CH0033', 'MCQ', 'Will C execute the statements written inside a comment?', '', 'No', '', 'Comments are only notes for humans. The C program ignores them.', 1, 4, true);
insert into questions (question_id, stage_id, chapter_id, type, prompt, code, answer, explanation, hint, xp, "order", active) values ('Q000165', 'STG001', 'CH0033', 'MCQ', 'Why are comments used in a C program?', '', 'To help programmers understand the code', '', 'Comments make the code easier for programmers to read and understand.', 1, 5, true);
insert into questions (question_id, stage_id, chapter_id, type, prompt, code, answer, explanation, hint, xp, "order", active) values ('Q000166', 'STG001', 'CH0034', 'MCQ', 'What is a variable in C?', '', 'A named storage box for a value', '', 'Think of a variable as a box with a name that can hold some information.', 1, 1, true);
insert into questions (question_id, stage_id, chapter_id, type, prompt, code, answer, explanation, hint, xp, "order", active) values ('Q000167', 'STG001', 'CH0034', 'MCQ', 'Which of the following is a correct way to create an integer variable?', '', 'int age;', '', 'The data type comes before the variable name.', 1, 2, true);
insert into questions (question_id, stage_id, chapter_id, type, prompt, code, answer, explanation, hint, xp, "order", active) values ('Q000168', 'STG001', 'CH0034', 'PREDICT_OUTPUT', 'What does this statement do?', 'int age = 18;', 'Creates age and stores 18 in it', '', 'Look at the = symbol. It puts the value 18 inside the variable age.', 1, 3, true);
insert into questions (question_id, stage_id, chapter_id, type, prompt, code, answer, explanation, hint, xp, "order", active) values ('Q000169', 'STG001', 'CH0034', 'MCQ', 'What is the purpose of the = symbol in a variable statement?', '', 'To assign/store a value', '', 'Think of = as putting a value into the variable.', 1, 4, true);
insert into questions (question_id, stage_id, chapter_id, type, prompt, code, answer, explanation, hint, xp, "order", active) values ('Q000170', 'STG001', 'CH0034', 'MCQ', 'Which data type is used to store a whole number?', '', 'int', '', 'Think of the data type we use for numbers like 10, 25, and 100.', 1, 5, true);
insert into questions (question_id, stage_id, chapter_id, type, prompt, code, answer, explanation, hint, xp, "order", active) values ('Q000171', 'STG001', 'CH0035', 'MCQ', 'Which data type is used to store a whole number?', '', 'int', '', 'Think about numbers like 10, 25, and 100 that have no decimal point.', 1, 1, true);
insert into questions (question_id, stage_id, chapter_id, type, prompt, code, answer, explanation, hint, xp, "order", active) values ('Q000172', 'STG001', 'CH0035', 'MCQ', 'What is the main purpose of printf()?', '', 'To display information on the screen', '', 'Think about the function we use when we want to show something on the screen.', 1, 2, true);
insert into questions (question_id, stage_id, chapter_id, type, prompt, code, answer, explanation, hint, xp, "order", active) values ('Q000173', 'STG001', 'CH0035', 'MCQ', 'Which data type is used to store one character?', '', 'char', '', 'Think about a single letter such as A, B, or S.', 1, 3, true);
insert into questions (question_id, stage_id, chapter_id, type, prompt, code, answer, explanation, hint, xp, "order", active) values ('Q000174', 'STG001', 'CH0035', 'BLANK', 'Fill in the blank: A __________ is like a storage box used to store a value in a C program.', '', 'Variable', '', 'Think of a named box where you can keep a value.', 1, 4, true);
insert into questions (question_id, stage_id, chapter_id, type, prompt, code, answer, explanation, hint, xp, "order", active) values ('Q000175', 'STG001', 'CH0035', 'MATCH_FOLLOWING', 'Match the following:', '', '0-2,1-3,2-1,3-0', '', 'Remember: int → whole numbers, float → decimal numbers, char → one character, and printf() → shows output.', 1, 5, true);
insert into questions (question_id, stage_id, chapter_id, type, prompt, code, answer, explanation, hint, xp, "order", active) values ('Q000176', 'STG001', 'CH0035', 'TYPE_CODE', '[BASIC] Print a Welcome Message

Write a C program to display:
Welcome to C Programming!', 'Expected Output:
Welcome to C Programming!', '#include <stdio.h>

int main()
{

   printf("Welcome to C Programming!");

   return 0;
}', '', 'Use the function that is used to display output on the screen.', 1, 6, true);
insert into questions (question_id, stage_id, chapter_id, type, prompt, code, answer, explanation, hint, xp, "order", active) values ('Q000177', 'STG001', 'CH0035', 'TYPE_CODE', '[BASIC] Display Your Details

Write a C program to display your name, age, and college name.', 'Expected Output:
Name: xyz
Age: 18
College: Rajalakshmi Engineering College', '#include <stdio.h>

int main()

{

   printf("Name: xyz\n");

   printf("Age: 18\n");

   printf("College: Rajalakshmi Engineering College");

   return 0;

}', '', 'You can use printf() separately for each line.', 1, 7, true);
insert into questions (question_id, stage_id, chapter_id, type, prompt, code, answer, explanation, hint, xp, "order", active) values ('Q000178', 'STG001', 'CH0035', 'TYPE_CODE', '[BASIC] Store and Display Age

Create an integer variable called age, store 18 in it, and display:
My age is 18', 'Expected Output:
My age is 18', '#include <stdio.h>

int main()
{

   int age = 18;

   printf("My age is %d", age);

   return 0;
}', '', 'First create the variable, then store 18, and finally use printf() to display it.', 1, 8, true);
insert into questions (question_id, stage_id, chapter_id, type, prompt, code, answer, explanation, hint, xp, "order", active) values ('Q000179', 'STG001', 'CH0035', 'TYPE_CODE', '[BASIC] Store and Display Marks

Create an integer variable called marks, store 85 in it, and display:
My marks are 85', 'Expected Output:
My marks are 85', '#include <stdio.h>

int main()
{

   int marks = 85;
   printf("My marks are %d", marks);

   return 0;

}', '', 'Create an int variable and use printf() with %d.', 1, 9, true);
insert into questions (question_id, stage_id, chapter_id, type, prompt, code, answer, explanation, hint, xp, "order", active) values ('Q000180', 'STG001', 'CH0035', 'TYPE_CODE', '[INTERMEDIATE] Student Information

Write a C program that creates variables for:
- Initial (char)
- Age (int)
- Percentage (float)

Display all three values.', 'Expected Output:
Initial: S
Age: 18
Percentage: 85.5', '#include <stdio.h>

int main()
{
   char initial = ''S'';
   int age = 18;
   float percentage = 85.5;

   printf("Initial: %c\n", initial);
   printf("Age: %d\n", age);
   printf("Percentage: %.1f", percentage);

   return 0;
}', '', 'Use a different data type for each kind of value.', 1, 10, true);
insert into questions (question_id, stage_id, chapter_id, type, prompt, code, answer, explanation, hint, xp, "order", active) values ('Q000181', 'STG001', 'CH0035', 'TYPE_CODE', '[INTERMEDIATE] Student Details Using Comments

Write a C program that displays:
----- STUDENT DETAILS -----
Name: xyz
Age: 18
Marks: 90
---------------------------

Rules:
- Store age in an int variable.
- Store marks in an int variable.
- Use comments to explain the variables.
- Use printf() to display the details.', 'Expected Output:
----- STUDENT DETAILS -----
Name: xyz
Age: 18
Marks: 90
---------------------------', '#include <stdio.h>

int main()
{

   // Store age
   int age = 18;

   // Store marks
   int marks = 90;

   printf("----- STUDENT DETAILS -----\n");
   printf("Name: xyz\n");
   printf("Age: %d\n", age);
   printf("Marks: %d\n", marks);
   printf("---------------------------");

   return 0;
}', '', 'Create the variables first, add comments using //, and then display them using printf().', 1, 11, true);
insert into questions (question_id, stage_id, chapter_id, type, prompt, code, answer, explanation, hint, xp, "order", active) values ('Q000182', 'STG001', 'CH0035', 'TYPE_CODE', '[INTERMEDIATE] Fix the Program

The following program contains mistakes. Correct it so that it displays:
My age is 18
My grade is A

Given Code:
#include <stdio.h>

int main()
{

   // Store age
   int age = 18

   // Store grade
   char grade = A;

   printf("My age is %d", age);
   printf("My grade is %c", grade);

   return 0;
}', 'Expected Output:
My age is 18
My grade is A', '#include <stdio.h>
int main()
{

   // Store age
   int age = 18;

   // Store grade
   char grade = ''A'';

   printf("My age is %d\n", age);
   printf("My grade is %c", grade);

   return 0;
}', '', 'Look carefully at the variable statements. Also remember how a char value is written.', 1, 12, true);
insert into questions (question_id, stage_id, chapter_id, type, prompt, code, answer, explanation, hint, xp, "order", active) values ('Q000183', 'STG001', 'CH0035', 'TYPE_CODE', '[HARD] Student Report

Write a C program to display:
===== STUDENT REPORT =====
Initial: S
Age: 18
Maths: 85
Science: 90
English: 88
==========================

Rules:
- Use char for initial.
- Use int for age and marks.
- Add comments.
- Use printf() for the output.', 'Expected Output:
===== STUDENT REPORT =====
Initial: S
Age: 18
Maths: 85
Science: 90
English: 88
==========================', '#include <stdio.h>

int main()
{

   // Store student details
   char initial = ''S'';
   int age = 18;

   // Store subject marks
   int maths = 85;
   int science = 90;
   int english = 88;

   printf("===== STUDENT REPORT =====\n");
   printf("Initial: %c\n", initial);
   printf("Age: %d\n", age);
   printf("Maths: %d\n", maths);
   printf("Science: %d\n", science);
   printf("English: %d\n", english);

   printf("==========================");

   return 0;

}', '', 'Create five variables first. Then use printf() to display each variable.', 1, 13, true);
insert into questions (question_id, stage_id, chapter_id, type, prompt, code, answer, explanation, hint, xp, "order", active) values ('Q000184', 'STG001', 'CH0035', 'TYPE_CODE', '[HARD] Personal Information Program

Create variables to store:
Name Initial: S
Age: 18
Height: 5.5
Grade: A

Then display all the information neatly.', 'Expected Output:
Name Initial: S
Age: 18
Height: 5.5
Grade: A', '#include <stdio.h>

int main()

{

   // Store personal information

   char initial = ''S'';

   int age = 18;
   float height = 5.5;

   char grade = ''A'';

   printf("Name Initial: %c\n", initial);

   printf("Age: %d\n", age);

   printf("Height: %.1f\n", height);

   printf("Grade: %c", grade);

   return 0;

}', '', 'Think about the type of each value: one character, whole number, decimal number, and one character.', 1, 14, true);
insert into questions (question_id, stage_id, chapter_id, type, prompt, code, answer, explanation, hint, xp, "order", active) values ('Q000185', 'STG001', 'CH0035', 'TYPE_CODE', '[HARD] Build a Complete C Program

Write a complete C program that displays:
STUDENT PROFILE
Initial: S
Age: 18
Marks: 92
Percentage: 92.5
Grade: A

Requirements:
1. Use char for initial.
2. Use int for age and marks.
3. Use float for percentage.
4. Create separate variables.
5. Add comments.
6. Use printf() to display the profile.
7. Follow the correct C program structure.', 'Expected Output:
************************
 STUDENT PROFILE
************************
Initial: S
Age: 18
Marks: 92
Percentage: 92.5
Grade: A
************************', '#include <stdio.h>

int main()
{

   // Store student profile
   char initial = ''S'';
   int age = 18;
   int marks = 92;
   float percentage = 92.5;
   char grade = ''A'';

   // Display student profile
   printf("************************\n");
   printf(" STUDENT PROFILE\n");
   printf("************************\n");
   printf("Initial: %c\n", initial);
   printf("Age: %d\n", age);
   printf("Marks: %d\n", marks);
   printf("Percentage: %.1f\n", percentage);
   printf("Grade: %c\n", grade);
   printf("************************");

   return 0;
}', '', 'Break the problem into small steps: Create variables → Store values → Use printf() → Format the output.', 1, 15, true);

-- options
insert into options (option_id, question_id, option_text, "order", active) values ('O0000361', 'Q000151', 'A programming language', 1, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000362', 'Q000151', 'A web browser', 2, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000363', 'Q000151', 'An operating system', 3, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000364', 'Q000151', 'A computer game', 4, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000365', 'Q000152', 'Execute the program', 1, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000366', 'Q000152', 'Write/Edit the source code', 2, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000367', 'Q000152', 'Link the program', 3, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000368', 'Q000152', 'Run the output', 4, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000369', 'Q000153', 'Editing', 1, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000370', 'Q000153', 'Compilation', 2, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000371', 'Q000153', 'Execution', 3, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000372', 'Q000153', 'Printing', 4, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000373', 'Q000154', 'Linking', 1, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000374', 'Q000154', 'Editing', 2, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000375', 'Q000154', 'Executing', 3, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000376', 'Q000154', 'Typing', 4, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000377', 'Q000155', 'We write the code', 1, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000378', 'Q000155', 'The program is run and produces output', 2, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000379', 'Q000155', 'Comments are added', 3, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000380', 'Q000155', 'Variables are created', 4, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000381', 'Q000156', 'scanf()', 1, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000382', 'Q000156', 'printf()', 2, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000383', 'Q000156', 'main()', 3, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000384', 'Q000156', 'return()', 4, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000385', 'Q000157', 'printf(Welcome to C);', 1, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000386', 'Q000157', 'printf("Welcome to C");', 2, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000387', 'Q000157', 'print("Welcome to C");', 3, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000388', 'Q000157', 'printf = "Welcome to C";', 4, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000389', 'Q000158', 'int main() {
   printf("Hello");
}', 1, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000390', 'Q000158', 'printf() {
   int main();
}', 2, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000391', 'Q000158', 'main
printf("Hello")', 3, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000392', 'Q000158', 'int printf() {
   main();
}', 4, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000393', 'Q000159', 'printf()', 1, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000394', 'Q000159', 'main()', 2, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000395', 'Q000159', 'display()', 3, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000396', 'Q000159', 'start()', 4, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000397', 'Q000160', 'Beginning of the program', 1, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000398', 'Q000160', 'End of the statement', 2, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000399', 'Q000160', 'Start of a comment', 3, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000400', 'Q000160', 'Name of the function', 4, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000401', 'Q000161', 'A note written for programmers', 1, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000402', 'Q000161', 'An output statement', 2, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000403', 'Q000161', 'A variable', 3, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000404', 'Q000161', 'A function', 4, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000405', 'Q000162', '/* */', 1, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000406', 'Q000162', '//', 2, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000407', 'Q000162', '##', 3, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000408', 'Q000162', '<>', 4, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000409', 'Q000163', '//', 1, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000410', 'Q000163', '<>', 2, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000411', 'Q000163', '/* */', 3, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000412', 'Q000163', '()', 4, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000413', 'Q000164', 'Yes', 1, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000414', 'Q000164', 'No', 2, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000415', 'Q000165', 'To help programmers understand the code', 1, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000416', 'Q000165', 'To increase the program''s speed', 2, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000417', 'Q000165', 'To produce output', 3, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000418', 'Q000165', 'To create variables', 4, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000419', 'Q000166', 'A named storage box for a value', 1, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000420', 'Q000166', 'A screen', 2, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000421', 'Q000166', 'A programming language', 3, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000422', 'Q000166', 'A comment', 4, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000423', 'Q000167', 'age int;', 1, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000424', 'Q000167', 'int age;', 2, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000425', 'Q000167', 'age = int;', 3, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000426', 'Q000167', 'integer age;', 4, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000427', 'Q000168', 'Prints 18', 1, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000428', 'Q000168', 'Creates age and stores 18 in it', 2, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000429', 'Q000168', 'Deletes age', 3, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000430', 'Q000168', 'Creates a comment', 4, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000431', 'Q000169', 'To print a value', 1, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000432', 'Q000169', 'To assign/store a value', 2, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000433', 'Q000169', 'To create a comment', 3, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000434', 'Q000169', 'To end the program', 4, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000435', 'Q000170', 'char', 1, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000436', 'Q000170', 'float', 2, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000437', 'Q000170', 'int', 3, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000438', 'Q000170', 'printf', 4, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000439', 'Q000171', 'float', 1, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000440', 'Q000171', 'char', 2, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000441', 'Q000171', 'int', 3, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000442', 'Q000171', 'printf()', 4, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000443', 'Q000172', 'To store a value', 1, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000444', 'Q000172', 'To display information on the screen', 2, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000445', 'Q000172', 'To create a comment', 3, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000446', 'Q000172', 'To create a data type', 4, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000447', 'Q000173', 'int', 1, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000448', 'Q000173', 'float', 2, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000449', 'Q000173', 'char', 3, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000450', 'Q000173', '//', 4, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000451', 'Q000175', 'int', 1, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000452', 'Q000175', 'float', 2, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000453', 'Q000175', 'char', 3, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000454', 'Q000175', 'printf()', 4, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000455', 'Q000175', 'Displays output', 5, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000456', 'Q000175', 'Stores one character', 6, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000457', 'Q000175', 'Stores whole numbers', 7, true);
insert into options (option_id, question_id, option_text, "order", active) values ('O0000458', 'Q000175', 'Stores decimal numbers', 8, true);

-- test_hints
insert into test_hints (hint_id, question_id, hint_text, active, "order") values ('H_Q000151', 'Q000151', 'Think about what C is used for — it is used to create programs.', true, 1);
insert into test_hints (hint_id, question_id, hint_text, active, "order") values ('H_Q000152', 'Q000152', 'Before a computer can run a program, we need to write the code.', true, 1);
insert into test_hints (hint_id, question_id, hint_text, active, "order") values ('H_Q000153', 'Q000153', 'This stage comes after editing and before the program can be executed.', true, 1);
insert into test_hints (hint_id, question_id, hint_text, active, "order") values ('H_Q000154', 'Q000154', 'Think of the stage that joins everything needed to create the final program.', true, 1);
insert into test_hints (hint_id, question_id, hint_text, active, "order") values ('H_Q000155', 'Q000155', 'This is the stage where you finally run the program.', true, 1);
insert into test_hints (hint_id, question_id, hint_text, active, "order") values ('H_Q000156', 'Q000156', 'Think about the function that is used to show something on the screen.', true, 1);
insert into test_hints (hint_id, question_id, hint_text, active, "order") values ('H_Q000157', 'Q000157', 'Text that we want to display should be written inside double quotation marks.', true, 1);
insert into test_hints (hint_id, question_id, hint_text, active, "order") values ('H_Q000158', 'Q000158', 'A basic C program needs the main() function and the statement that displays the output.', true, 1);
insert into test_hints (hint_id, question_id, hint_text, active, "order") values ('H_Q000159', 'Q000159', 'Think about the function that acts as the starting point of a C program.', true, 1);
insert into test_hints (hint_id, question_id, hint_text, active, "order") values ('H_Q000160', 'Q000160', 'Look at the symbol ; — it tells C that a statement has ended.', true, 1);
insert into test_hints (hint_id, question_id, hint_text, active, "order") values ('H_Q000161', 'Q000161', 'Think of a comment as a small note that helps people understand the code.', true, 1);
insert into test_hints (hint_id, question_id, hint_text, active, "order") values ('H_Q000162', 'Q000162', 'Look for the symbol that uses two forward slashes.', true, 1);
insert into test_hints (hint_id, question_id, hint_text, active, "order") values ('H_Q000163', 'Q000163', 'This comment starts with /* and ends with */.', true, 1);
insert into test_hints (hint_id, question_id, hint_text, active, "order") values ('H_Q000164', 'Q000164', 'Comments are only notes for humans. The C program ignores them.', true, 1);
insert into test_hints (hint_id, question_id, hint_text, active, "order") values ('H_Q000165', 'Q000165', 'Comments make the code easier for programmers to read and understand.', true, 1);
insert into test_hints (hint_id, question_id, hint_text, active, "order") values ('H_Q000166', 'Q000166', 'Think of a variable as a box with a name that can hold some information.', true, 1);
insert into test_hints (hint_id, question_id, hint_text, active, "order") values ('H_Q000167', 'Q000167', 'The data type comes before the variable name.', true, 1);
insert into test_hints (hint_id, question_id, hint_text, active, "order") values ('H_Q000168', 'Q000168', 'Look at the = symbol. It puts the value 18 inside the variable age.', true, 1);
insert into test_hints (hint_id, question_id, hint_text, active, "order") values ('H_Q000169', 'Q000169', 'Think of = as putting a value into the variable.', true, 1);
insert into test_hints (hint_id, question_id, hint_text, active, "order") values ('H_Q000170', 'Q000170', 'Think of the data type we use for numbers like 10, 25, and 100.', true, 1);
insert into test_hints (hint_id, question_id, hint_text, active, "order") values ('H_Q000171', 'Q000171', 'Think about numbers like 10, 25, and 100 that have no decimal point.', true, 1);
insert into test_hints (hint_id, question_id, hint_text, active, "order") values ('H_Q000172', 'Q000172', 'Think about the function we use when we want to show something on the screen.', true, 1);
insert into test_hints (hint_id, question_id, hint_text, active, "order") values ('H_Q000173', 'Q000173', 'Think about a single letter such as A, B, or S.', true, 1);
insert into test_hints (hint_id, question_id, hint_text, active, "order") values ('H_Q000174', 'Q000174', 'Think of a named box where you can keep a value.', true, 1);
insert into test_hints (hint_id, question_id, hint_text, active, "order") values ('H_Q000175', 'Q000175', 'Remember: int → whole numbers, float → decimal numbers, char → one character, and printf() → shows output.', true, 1);
insert into test_hints (hint_id, question_id, hint_text, active, "order") values ('H_Q000176', 'Q000176', 'Use the function that is used to display output on the screen.', true, 1);
insert into test_hints (hint_id, question_id, hint_text, active, "order") values ('H_Q000177', 'Q000177', 'You can use printf() separately for each line.', true, 1);
insert into test_hints (hint_id, question_id, hint_text, active, "order") values ('H_Q000178', 'Q000178', 'First create the variable, then store 18, and finally use printf() to display it.', true, 1);
insert into test_hints (hint_id, question_id, hint_text, active, "order") values ('H_Q000179', 'Q000179', 'Create an int variable and use printf() with %d.', true, 1);
insert into test_hints (hint_id, question_id, hint_text, active, "order") values ('H_Q000180', 'Q000180', 'Use a different data type for each kind of value.', true, 1);
insert into test_hints (hint_id, question_id, hint_text, active, "order") values ('H_Q000181', 'Q000181', 'Create the variables first, add comments using //, and then display them using printf().', true, 1);
insert into test_hints (hint_id, question_id, hint_text, active, "order") values ('H_Q000182', 'Q000182', 'Look carefully at the variable statements. Also remember how a char value is written.', true, 1);
insert into test_hints (hint_id, question_id, hint_text, active, "order") values ('H_Q000183', 'Q000183', 'Create five variables first. Then use printf() to display each variable.', true, 1);
insert into test_hints (hint_id, question_id, hint_text, active, "order") values ('H_Q000184', 'Q000184', 'Think about the type of each value: one character, whole number, decimal number, and one character.', true, 1);
insert into test_hints (hint_id, question_id, hint_text, active, "order") values ('H_Q000185', 'Q000185', 'Break the problem into small steps: Create variables → Store values → Use printf() → Format the output.', true, 1);

-- question_terms
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000151', 'TERM031', 'programming language', 1, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000152', 'TERM032', 'first stage', 1, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000152', 'TERM033', 'programming', 2, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000152', 'TERM034', 'source code', 3, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000153', 'TERM035', 'stage', 1, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000153', 'TERM034', 'source code', 2, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000153', 'TERM036', 'machine-understandable', 3, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000154', 'TERM035', 'stage', 1, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000154', 'TERM037', 'required files', 2, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000154', 'TERM038', 'libraries', 3, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000154', 'TERM039', 'final program', 4, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000155', 'TERM040', 'execution', 1, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000155', 'TERM035', 'stage', 2, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000155', 'TERM041', 'program', 3, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000155', 'TERM042', 'output', 4, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000156', 'TERM042', 'output', 1, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000157', 'TERM043', 'Build', 1, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000157', 'TERM044', 'printf()', 2, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000158', 'TERM041', 'program', 1, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000158', 'TERM045', 'main()', 2, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000159', 'TERM046', 'structure', 1, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000160', 'TERM047', 'syntax', 1, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000161', 'TERM048', 'comment', 1, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000161', 'TERM033', 'programming', 2, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000162', 'TERM049', 'symbol', 1, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000162', 'TERM050', 'single-line', 2, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000163', 'TERM049', 'symbols', 1, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000163', 'TERM051', 'multi-line', 2, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000163', 'TERM048', 'comment', 3, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000164', 'TERM052', 'execute', 1, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000164', 'TERM053', 'statements', 2, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000164', 'TERM048', 'comment', 3, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000165', 'TERM048', 'comments', 1, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000165', 'TERM041', 'program', 2, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000166', 'TERM054', 'variable', 1, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000167', 'TERM055', 'integer', 1, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000167', 'TERM054', 'variable', 2, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000168', 'TERM053', 'statement', 1, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000169', 'TERM056', 'purpose', 1, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000169', 'TERM049', 'symbol', 2, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000169', 'TERM054', 'variable', 3, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000169', 'TERM053', 'statement', 4, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000170', 'TERM057', 'data type', 1, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000170', 'TERM058', 'whole number', 2, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000171', 'TERM057', 'data type', 1, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000171', 'TERM058', 'whole number', 2, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000172', 'TERM059', 'main purpose', 1, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000173', 'TERM057', 'data type', 1, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000173', 'TERM060', 'character', 2, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000174', 'TERM061', 'value', 1, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000174', 'TERM041', 'program', 2, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000175', 'TERM062', 'int', 1, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000175', 'TERM063', 'float', 2, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000175', 'TERM064', 'char', 3, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000175', 'TERM044', 'printf()', 4, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000176', 'TERM065', 'display', 1, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000176', 'TERM041', 'program', 2, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000177', 'TERM044', 'printf()', 1, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000177', 'TERM045', 'main( ) {', 2, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000178', 'TERM066', 'integer variable', 1, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000178', 'TERM067', 'age', 2, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000178', 'TERM065', 'display', 3, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000179', 'TERM066', 'integer variable', 1, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000180', 'TERM062', 'int', 1, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000180', 'TERM063', 'float', 2, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000180', 'TERM064', 'char', 3, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000181', 'TERM062', 'int', 1, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000181', 'TERM048', 'comments', 2, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000181', 'TERM054', 'variables', 3, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000182', 'TERM041', 'program', 1, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000182', 'TERM045', 'main()', 2, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000183', 'TERM062', 'int', 1, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000183', 'TERM064', 'char', 2, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000183', 'TERM044', 'printf()', 3, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000184', 'TERM062', 'int', 1, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000184', 'TERM063', 'float', 2, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000184', 'TERM064', 'char', 3, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000184', 'TERM044', 'printf()', 4, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000185', 'TERM068', 'separate variables', 1, true);
insert into question_terms (question_id, term_id, display_text, "order", active) values ('Q000185', 'TERM069', 'program structure', 2, true);

-- deactivate
-- Soft-remove the old Stage 0 ("Constants, Variables and Data Types") from the active
-- learning path. Data is preserved (active=false), not deleted, per project convention.
update stages set active = false where stage_id = 'STG000';
update chapters set active = false where stage_id = 'STG000';
update learn_content set active = false where stage_id = 'STG000';
update questions set active = false where stage_id = 'STG000';
update options set active = false where question_id in (select question_id from questions where stage_id = 'STG000');
update test_hints set active = false where question_id in (select question_id from questions where stage_id = 'STG000');
update question_terms set active = false where question_id in (select question_id from questions where stage_id = 'STG000');

-- prerequisites
-- P001 (first Practice Bank challenge) previously required completing the old STG000.
-- Since STG000 is now deactivated (see above), bootstrap()'s active-stage list will
-- never contain it again, so stageCompleteIds could never include it -- Practice Bank
-- would stay permanently locked. Repoint the same rule at the new Stage 0 (STG001) so
-- completing the new Foundations chapters continues to unlock Practice, as intended.
update prerequisites set prerequisite_id = 'STG001' where target_id = 'P001' and prerequisite_id = 'STG000';
